// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate deploy, etc.) need a direct connection — Neon's
    // pooled DATABASE_URL (PgBouncer, transaction mode) doesn't reliably
    // support the advisory locks Prisma Migrate relies on. Vercel's Neon
    // integration sets DATABASE_URL_UNPOOLED alongside the pooled
    // DATABASE_URL; local dev only has the latter, hence the fallback.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
